name: Deploy Backend to EC2 (PM2)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive backend
        run: |
          tar --exclude='./backend/node_modules' -czf backend.tar.gz backend

      # (선택) 원격 폴더 보장: 먼저 폴더 만들어 두고 권한 맞추기
      - name: Ensure deploy dir exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.EC2_DEPLOY_DIR }}
            sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} ${{ secrets.EC2_DEPLOY_DIR }}

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend.tar.gz"
          target: ${{ secrets.EC2_DEPLOY_DIR }}

      - name: Deploy on EC2 (untar, install, pm2 reload)
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              set -e
              cd ${{ secrets.EC2_DEPLOY_DIR }}
              tar -xzf backend.tar.gz
              rm -f backend.tar.gz
              cd backend
              npm install --omit=dev --no-fund --no-audit
              if pm2 describe starter-backend > /dev/null; then
                pm2 reload ecosystem.config.js
              else
                pm2 start ecosystem.config.js
              fi
              pm2 save
