name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # ✅ 프로덕션 환경변수 주입 (여기가 핵심!)
      #    VITE_API_BASE는 CloudFront에서 접근 가능한 HTTPS API 엔드포인트여야 함.
      - name: Create .env.production
        run: |
          echo "VITE_API_BASE=${{ secrets.PROD_API_BASE }}" > .env.production
          # 선택: 빌드 플래그나 스테이지 값이 있으면 여기에 추가
          echo "VITE_APP_STAGE=production" >> .env.production
          cat .env.production

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      # AWS 자격 증명 등록
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # ✅ AWS CLI v2 설치
      - name: Install AWS CLI v2
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      # 1️⃣ 해시된 자산(JS/CSS 등): 캐시 길게
      - name: Sync hashed assets with long cache
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude "index.html" \
            --exclude "404.html" \
            --cache-control "public,max-age=31536000,immutable"

      # 2️⃣ index.html: 캐시 없음 (항상 최신)
      - name: Upload index.html with no-cache
        run: |
          aws s3 cp ./dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      # (선택) SPA 라우팅용 404.html도 동일하게 no-cache 업로드
      - name: Upload 404.html with no-cache (optional for SPA)
        if: ${{ hashFiles('frontend/dist/404.html') != '' }}
        run: |
          aws s3 cp ./dist/404.html s3://${{ secrets.S3_BUCKET }}/404.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      # 3️⃣ CloudFront 캐시 무효화
      #    보통 index.html과 / 만 무효화하면 충분 (해시 자산은 immutable)
      - name: Invalidate CloudFront (index & root)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/index.html" "/"
